[package]
name = "build-workflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.69.4"
cc = "1.0.88"
regex = "1.10.3"

[dependencies]
cudarc = { path = "../.." }